# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: # 基础 URL（一般保持为空）
url: https://magicianplus.github.io # 网站的完整 URL，发布后会指向该地址
date_format: "ordinal" # 日期格式
title: 编程组 # 网站标题，可修改为你自己的博客名称
subtitle: "山西农业大学无人机创新团队编程组知识博客" # 网站副标题，可修改为你的描述
description: "我们是一个充满热情与活力的团队，专注于无人机技术的创新与应用。在这里，我们将共同学习C语言和STM32微控制器的相关知识，为未来的项目开发奠定坚实的基础。
我们的目标是通过在编程组的深入学习，不断提高自己的知识水平和动手能力。我们将积极参与各类项目研发和学科竞赛，在实践中锻炼自己，追求卓越。
期待与你一起分享学习心得和项目经验，共同成长！" # 网站描述，用于 SEO
keywords: 编程, 无人机, C语言, STM32, 技术博客 # 关键词，利于搜索引擎收录
timezone: China/Taiyuan # 修改为你所在的时区 # 时区设置，建议保持与你所在的时区一致
encoding: "utf-8" # 编码格式
side_bar_repo_limit: 5 # 侧边栏显示的仓库数量
repository: magicianplus/magicianplus.github.io # 替换为你的 GitHub 仓库路径 # 仓库地址
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]

# ---------------- #
#      Author      #
# ---------------- #
author: YYJ # 作者名，可修改为你的名字
location: 山西, 中国 # 修改为你的所在地 # 所在地信息
email: 1986388918@qq.com # 邮箱地址
organization: 
organization_url: 
github_username: Magicianplus

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  # -
  #   href: /management/
  #   label: 技术管理

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/

comments_provider: gitalk
gitalk:
  owner: magicianplus # GitHub 用户名，修改为你的用户名
  repo: blog_comments # 用于存储评论的仓库，需先在 GitHub 上创建
  clientID: Ov23li2ltGxIAnQT6trk  # GitHub OAuth 应用的 clientID
  clientSecret: 14d24f19d085d456404d9772505351d3e3773492 # GitHub OAuth 应用的 clientSecret

lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
