# ---------------- #
#   Main Configs   #
#   主要配置        #
# ---------------- #
baseurl: 
  url: https://magicianplus.github.io # 网站的完整 URL
  date_format: "ordinal"
  title: 编程组 # 网站标题
  subtitle: "山西农业大学无人机创新团队编程组知识博客" # 网站副标题
  description: "我们是一个充满热情与活力的团队，专注于无人机技术的创新与应用。在这里，我们将共同学习C语言和STM32微控制器的相关知识，为未来的项目开发奠定坚实的基础。我们的目标是通过在编程组的深入学习，不断提高自己的知识水平和动手能力。我们将积极参与各类项目研发和学科竞赛，在实践中锻炼自己，追求卓越。期待与你一起分享学习心得和项目经验，共同成长！" # 网站描述
  keywords: 编程, 无人机, C语言, STM32, 技术博客 # 关键词
  timezone: China/Taiyuan # 时区设置
  encoding: "utf-8"
  side_bar_repo_limit: 5
  repository: magicianplus/magicianplus.github.io # 替换为你的 GitHub 仓库路径
  
  # 对 css 和 js 资源的 cdn 加速配置
  cdn:
    jsdelivr:
      enabled: true
  
  # 组件配置
  components:
    busuanzi:
      enabled: true
      start_date: 2020-05-03
  
  # ---------------- #
  #      Author      #
  #    作者信息       #
  # ---------------- #
  author: YYJ # 修改为你的名字
  location: 山西, 中国 # 修改为你的所在地
  email: 1986388918@qq.com # 邮箱地址
  
  # ---------------- #
  #    Navigation    #
  #     导航栏配置   #
  # ---------------- #
  navs:
    -
      href: /
      label: 首页
    -
      href: /categories/
      label: 分类
    -
      href: /wiki/
      label: 维基
    -
      href: /links/
      label: 链接
    -
      href: /about/
      label: 关于
  
  # ---------------- #
  #      Jekyll      #
  #    Jekyll配置    #
  # ---------------- #
  markdown: kramdown
  highlighter: rouge
  paginate: 10
  permalink: /:year/:month/:day/:title/
  plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
  
  # ---------------- #
  #      Comments    #
  #    评论系统配置  #
  # ---------------- #
  comments_provider: gitalk
  gitalk:
    owner: magicianplus
    repo: blog_comments
    clientID: Ov23li2ltGxIAnQT6trk
    clientSecret: 14d24f19d085d456404d9772505351d3e3773492
  
  # ---------------- #
  #      Search      #
  #    搜索功能配置  #
  # ---------------- #
  simple_jekyll_search:
    fulltext: false
    limit: 10
  
  # ---------------- #
  #      Google      #
  #    Google相关配置 #
  # ---------------- #
  google:
    analytics_id: UA-80669434-1
  