# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://magicianplus.github.io
date_format: "ordinal"
title: 编程组
subtitle: "山西农业大学无人机创新团队编程组知识博客"
description: "我们是一个充满热情与活力的团队，专注于无人机技术的创新与应用。在这里，我们将共同学习C语言和STM32微控制器的相关知识，为未来的项目开发奠定坚实的基础。我们的目标是通过在编程组的深入学习，不断提高自己的知识水平和动手能力。我们将积极参与各类项目研发和学科竞赛，在实践中锻炼自己，追求卓越。期待与你一起分享学习心得和项目经验，共同成长！"
keywords: 编程, 无人机, C语言, STM32, 技术博客
timezone: China/Taiyuan
encoding: "utf-8"
side_bar_repo_limit: 5
repository: magicianplus/magicianplus.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]

# ---------------- #
#      Author      #
# ---------------- #
author: YYJ
organization: 
organization_url: 
github_username: magicianplus
location: 山西, 中国
email: 1986388918@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  # -
  #   href: /management/
  #   label: 技术管理

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: magicianplus
    repo: blog_comments
    oauth:
        client_id: Ov23li2ltGxIAnQT6trk
        client_secret: 14d24f19d085d456404d9772505351d3e3773492
# https://github.com/gitalk/gitalk#install
# 参考：https://www.ppkanshu.com/index.php/post/4158.html
gitalk:
    owner: magicianplus
    repo: blog_comments
    clientID: Ov23li2ltGxIAnQT6trk
    clientSecret: 14d24f19d085d456404d9772505351d3e3773492
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
