# ---------------- #
#   Main Configs   #
#   主要配置        #
# ---------------- #
baseurl: # 基础 URL（一般保持为空）
url: https://magicianplus.github.io # 网站的完整 URL，发布后会指向该地址
date_format: "ordinal" # 日期格式
title: 编程组 # 网站标题，可修改为你自己的博客名称
subtitle: "山西农业大学无人机创新团队编程组知识博客" # 网站副标题，可修改为你的描述
description: "我们是一个充满热情与活力的团队，专注于无人机技术的创新与应用。在这里，我们将共同学习C语言和STM32微控制器的相关知识，为未来的项目开发奠定坚实的基础。
我们的目标是通过在编程组的深入学习，不断提高自己的知识水平和动手能力。我们将积极参与各类项目研发和学科竞赛，在实践中锻炼自己，追求卓越。
期待与你一起分享学习心得和项目经验，共同成长！" # 网站描述，用于 SEO
keywords: 编程, 无人机, C语言, STM32, 技术博客 # 关键词，利于搜索引擎收录
timezone: China/Taiyuan # 修改为你所在的时区 # 时区设置，建议保持与你所在的时区一致
encoding: "utf-8" # 编码格式
side_bar_repo_limit: 5 # 侧边栏显示的仓库数量
repository: magicianplus/magicianplus.github.io # 替换为你的 GitHub 仓库路径 # 仓库地址

# 对 css 和 js 资源的 cdn 加速配置
cdn:
  jsdelivr:
    enabled: true # 是否启用 jsdelivr 加速

# 组件配置
components:
  # 不蒜子访问统计
  busuanzi:
    enabled: true # 是否启用不蒜子统计访问量
    start_date: 2020-05-03 # 开始统计日期

# ---------------- #
#      Author      #
#    作者信息       #
# ---------------- #
author: YYJ # 作者名，可修改为你的名字
location: 山西, 中国 # 修改为你的所在地 # 所在地信息
email: 1986388918@qq.com # 邮箱地址

# ---------------- #
#    Navigation    #
#     导航栏配置   #
# ---------------- #
navs:
  -
    href: /
    label: 首页 # 首页链接
  -
    href: /categories/
    label: 分类 # 分类页面链接
  -
    href: /wiki/
    label: 维基 # 维基页面链接
  -
    href: /links/
    label: 链接 # 链接页面
  -
    href: /about/
    label: 关于 # 关于页面

# ---------------- #
#      Jekyll      #
#    Jekyll配置    #
# ---------------- #
markdown: kramdown # 使用的 Markdown 解析器
highlighter: rouge # 代码高亮的插件
paginate: 10 # 每页显示的文章数量
permalink: /:year/:month/:day/:title/ # 文章链接格式
plugins:
  - jekyll-paginate # 分页插件
  - jekyll-sitemap # 生成 sitemap
  - jekyll-feed # 生成 RSS feed
  - jemoji # 支持 Emoji 表情

# ---------------- #
#      Comments    #
#    评论系统配置  #
# ---------------- #
# 使用 Gitalk 作为评论系统，需要配置 GitHub 应用的信息
comments_provider: gitalk
gitalk:
  owner: magicianplus # GitHub 用户名，修改为你的用户名
  repo: blog_comments # 用于存储评论的仓库，需先在 GitHub 上创建
  clientID: Ov23li2ltGxIAnQT6trk  # GitHub OAuth 应用的 clientID
  clientSecret: 14d24f19d085d456404d9772505351d3e3773492 # GitHub OAuth 应用的 clientSecret

# ---------------- #
#      Search      #
#    搜索功能配置  #
# ---------------- #
simple_jekyll_search:
  fulltext: false # 是否启用全文搜索
  limit: 10 # 最多显示的搜索结果数量

# ---------------- #
#      Google      #
#    Google相关配置 #
# ---------------- #
google:
  analytics_id: UA-80669434-1 # Google Analytics 追踪 ID
